gui:
  scrollHeight: 10
  timeFormat: '2006-01-02 15:04:05 MST'
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: false
  nerdFontsVersion: 3
  skipRewordInEditorWarning: true
  border: 'double'
git:
  branchLogCmd:      'git log       --graph --color=always --abbrev-commit --decorate --date=iso --pretty=medium {{branchName}} --'
  allBranchesLogCmd: 'git log --all --graph --color=always --abbrev-commit --decorate --date=iso  --pretty=medium'
update:
  method: never
notARepository: 'quit'
promptToReturnFromSubprocess: false
keybinding:
  files:
    # swap default bindings
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
    toggleStagedAll: '<c-8>' # virtually disable stage/unstage all
